[[LibGD]]
arch = "aarch64"
git-tree-sha1 = "2aa096bd0b1ae6ae53001aabe3bbddcde2a2bada"
libc = "glibc"
os = "linux"

    [[LibGD.download]]
    sha256 = "8a08c54e5c9b46bba2cb0dc169e62a5d483fd952becd577e97db670dcf0c4d66"
    url = "https://github.com/JuliaBinaryWrappers/LibGD_jll.jl/releases/download/LibGD-v2.3.0+0/LibGD.v2.3.0.aarch64-linux-gnu.tar.gz"
[[LibGD]]
arch = "aarch64"
git-tree-sha1 = "35a8045977a17d24f406b496730e9eddb58e9e9d"
libc = "musl"
os = "linux"

    [[LibGD.download]]
    sha256 = "f6d2d3edd4587c476a59a366e1f1a0854bd2ea36f80aba533455060f845a6738"
    url = "https://github.com/JuliaBinaryWrappers/LibGD_jll.jl/releases/download/LibGD-v2.3.0+0/LibGD.v2.3.0.aarch64-linux-musl.tar.gz"
[[LibGD]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "b4a3f531cb3d9f54f37c7c01524d37713a7d747c"
libc = "glibc"
os = "linux"

    [[LibGD.download]]
    sha256 = "a990b78f51b47bb932fff43681d613fea9a8f1a004a9b23c18210ed0e41ae358"
    url = "https://github.com/JuliaBinaryWrappers/LibGD_jll.jl/releases/download/LibGD-v2.3.0+0/LibGD.v2.3.0.armv7l-linux-gnueabihf.tar.gz"
[[LibGD]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "843085c025ea35447ffbf6c13266c92355d25ef3"
libc = "musl"
os = "linux"

    [[LibGD.download]]
    sha256 = "1d9cf7cfd9e6dc25f04ef0350b1ca2dad06800357c068a42fb032943bd1e9a85"
    url = "https://github.com/JuliaBinaryWrappers/LibGD_jll.jl/releases/download/LibGD-v2.3.0+0/LibGD.v2.3.0.armv7l-linux-musleabihf.tar.gz"
[[LibGD]]
arch = "i686"
git-tree-sha1 = "30e6954461db3ba0307405df23de93ebef5c7a02"
libc = "glibc"
os = "linux"

    [[LibGD.download]]
    sha256 = "4232f613d3d4a0034f97a58dc203ec8f4339233d92883b9bf94efc964aa4275d"
    url = "https://github.com/JuliaBinaryWrappers/LibGD_jll.jl/releases/download/LibGD-v2.3.0+0/LibGD.v2.3.0.i686-linux-gnu.tar.gz"
[[LibGD]]
arch = "i686"
git-tree-sha1 = "bd1a666cac00c1209adf7914861efb1aab280c38"
libc = "musl"
os = "linux"

    [[LibGD.download]]
    sha256 = "eac6564c3799fd998c98defbd7aad74e2ce6dad8ced9751bb4c3ba2e37da6927"
    url = "https://github.com/JuliaBinaryWrappers/LibGD_jll.jl/releases/download/LibGD-v2.3.0+0/LibGD.v2.3.0.i686-linux-musl.tar.gz"
[[LibGD]]
arch = "i686"
git-tree-sha1 = "fd16cbe43790e08acfcc33fc6f6b19e693cd140b"
os = "windows"

    [[LibGD.download]]
    sha256 = "f3de7a9b34232db0e322e81d887dcef62a3f4ba60696bf90fd633d2d982efa02"
    url = "https://github.com/JuliaBinaryWrappers/LibGD_jll.jl/releases/download/LibGD-v2.3.0+0/LibGD.v2.3.0.i686-w64-mingw32.tar.gz"
[[LibGD]]
arch = "powerpc64le"
git-tree-sha1 = "8cd1189af7af20653b8b1530d5ed3b073a04fa93"
libc = "glibc"
os = "linux"

    [[LibGD.download]]
    sha256 = "5db2b6e7c97ea6dd6612f9a00bc7e1729f201374699cde105c605fb910de8849"
    url = "https://github.com/JuliaBinaryWrappers/LibGD_jll.jl/releases/download/LibGD-v2.3.0+0/LibGD.v2.3.0.powerpc64le-linux-gnu.tar.gz"
[[LibGD]]
arch = "x86_64"
git-tree-sha1 = "67aab5fcb8a6809aec745d168d30ffddb988c6db"
os = "macos"

    [[LibGD.download]]
    sha256 = "1704e760ec08b24aae5d2fa14a28c0bc8655f98b5c66dd2ea77e8b56be4098fd"
    url = "https://github.com/JuliaBinaryWrappers/LibGD_jll.jl/releases/download/LibGD-v2.3.0+0/LibGD.v2.3.0.x86_64-apple-darwin.tar.gz"
[[LibGD]]
arch = "x86_64"
git-tree-sha1 = "342eb7be98586ec7a4d648e3f6dc5913dc8d0c12"
libc = "glibc"
os = "linux"

    [[LibGD.download]]
    sha256 = "4b5c938682b5c81d9e8e4714c9281aea160d2a486e8bfb27201d2b12eba0393c"
    url = "https://github.com/JuliaBinaryWrappers/LibGD_jll.jl/releases/download/LibGD-v2.3.0+0/LibGD.v2.3.0.x86_64-linux-gnu.tar.gz"
[[LibGD]]
arch = "x86_64"
git-tree-sha1 = "9815fed9556a1414ce2ecb276f2bb1b85f4e7697"
libc = "musl"
os = "linux"

    [[LibGD.download]]
    sha256 = "88bcbbdf722decba6f930e49fbc4181f3f05295f2cfe3e6f7cef0627c43b7b06"
    url = "https://github.com/JuliaBinaryWrappers/LibGD_jll.jl/releases/download/LibGD-v2.3.0+0/LibGD.v2.3.0.x86_64-linux-musl.tar.gz"
[[LibGD]]
arch = "x86_64"
git-tree-sha1 = "18d63601390a243f143e15358eb050605697cc62"
os = "freebsd"

    [[LibGD.download]]
    sha256 = "fe170b7bb52fdc45b561b55aa848e17b95f716126ed36fda88bf5ef0ee364bef"
    url = "https://github.com/JuliaBinaryWrappers/LibGD_jll.jl/releases/download/LibGD-v2.3.0+0/LibGD.v2.3.0.x86_64-unknown-freebsd.tar.gz"
[[LibGD]]
arch = "x86_64"
git-tree-sha1 = "4c321ea83282f557b9ca0389a21d1227f428c35c"
os = "windows"

    [[LibGD.download]]
    sha256 = "ebbcc183d65ee441abd490d856efcd15ca903f44542f35f940748a1668c0e916"
    url = "https://github.com/JuliaBinaryWrappers/LibGD_jll.jl/releases/download/LibGD-v2.3.0+0/LibGD.v2.3.0.x86_64-w64-mingw32.tar.gz"
